create table if not exists public.scans (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  device_id text not null,
  categoria text not null check (categoria in ('financeira', 'saude', 'legal')),
  titulo text not null,
  valor text not null,
  vencimento text not null,
  imposto_estimado text not null,
  beneficiario text,
  alerta_fraude boolean not null default false,
  motivo_fraude text,
  raw_response text
);

create index if not exists scans_device_id_created_at_idx
  on public.scans (device_id, created_at desc);
